# Generated by Django 6.0.7 on 2026-07-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='background_color',
            field=models.CharField(blank=True, default='#1a237e', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='text_bg_color',
            field=models.CharField(blank=True, default='rgba(0,0,0,0.5)', max_length=20, null=True),
        ),
    ]
