# Generated by Django 6.0.7 on 2026-07-10 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('landlord', 'Landlord'), ('admin', 'Admin')], default='student', max_length=10)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_online', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_privacy', models.CharField(choices=[('public', 'Everyone'), ('friends', 'Friends Only'), ('private', 'Only Me')], default='private', max_length=10)),
                ('location_privacy', models.CharField(choices=[('public', 'Everyone'), ('friends', 'Friends Only'), ('private', 'Only Me')], default='friends', max_length=10)),
                ('year_privacy', models.CharField(choices=[('public', 'Everyone'), ('friends', 'Friends Only'), ('private', 'Only Me')], default='friends', max_length=10)),
                ('phone_privacy', models.CharField(choices=[('public', 'Everyone'), ('friends', 'Friends Only'), ('private', 'Only Me')], default='private', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_documents', models.FileField(blank=True, null=True, upload_to='verifications/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
