# Generated by Django 6.0.7 on 2026-07-10 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('landlord', 'Landlord'), ('admin', 'Admin'), ('superuser', 'Superuser')], default='student', max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('course', models.CharField(blank=True, max_length=100)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('property_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('email_privacy', models.CharField(choices=[('public', 'Everyone'), ('friends', 'Friends Only'), ('private', 'Only Me')], default='private', max_length=10)),
                ('location_privacy', models.CharField(choices=[('public', 'Everyone'), ('friends', 'Friends Only'), ('private', 'Only Me')], default='friends', max_length=10)),
                ('year_privacy', models.CharField(choices=[('public', 'Everyone'), ('friends', 'Friends Only'), ('private', 'Only Me')], default='friends', max_length=10)),
                ('phone_privacy', models.CharField(choices=[('public', 'Everyone'), ('friends', 'Friends Only'), ('private', 'Only Me')], default='private', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_documents', models.FileField(blank=True, null=True, upload_to='verifications/')),
                ('is_online', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
